{
 "title": "Taller Monitorización",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Fastapi HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"fastapi-otel-poc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of /error requests in 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{route=\"/error\"}[5m]))\n) \n/\n(\n  sum(rate(http_requests_total[5m]))\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of /external-call requests in 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{route=\"/external-call\"}[5m]))\n) \n/\n(\n  sum(rate(http_requests_total[5m]))\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of /compute requests in 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{route=\"/compute\"}[5m]))\n) \n/\n(\n  sum(rate(http_requests_total[5m]))\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of /process requests in 5m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{route=\"/process\"}[5m]))\n) \n/\n(\n  sum(rate(http_requests_total[5m]))\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Too many open files error 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"fastapi-app\"} |= \"too many open files\" [1m])\n"
    }
   ]
  },
  {
   "title": "Too many open files error 10m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"fastapi-app\"} |= \"too many open files\" [10m])\n"
    }
   ]
  },
  {
   "title": "Too many open files error 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"fastapi-app\"} |= \"too many open files\" [5m])\n"
    }
   ]
  },
  { "title": "K8S Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Available K8S memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": ":node_memory_MemAvailable_bytes:sum / 1073741824",
     "legendFormat": "Available memory"
    }
   ]
  },
  {
   "title": "K8S Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio * 100", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "K8S Cluster Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8S Cluster CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio * 100", "legendFormat": "__auto" }
   ]
  }
 ]
}